apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: angular-app123
        image: 706274417810.dkr.ecr.ap-south-1.amazonaws.com/kpdocker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
          name: http
          protocol: TCP
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app-svc
spec:
  selector:
    app: angular-app
  ports:
    - name: http
      protocol: TCP
      port: 8090
      targetPort: 8090
  type: LoadBalancer
